---
# NOTE(gyee): we'll only include the first one that matches. The rest will be ignored.
- name: Include OS family vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Include OS distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "main.yml"

- name: Include platform-specific common tasks
  include_tasks: "_{{ ansible_os_family | lower }}.yml"

- name: Add metallb helm repo
  kubernetes.core.helm_repository:
    repo_url: "{{ metallb_helm_repo_url }}"
    name: "{{ metallb_helm_repo_name }}"

- name: Deploy metallb helm chart
  shell: |
    env HELM_EXPERIMENTAL_OCI=1 \
    helm upgrade --install {{ metallb_release }} {{ metallb_helm_chart_ref }} \
      --create-namespace --namespace {{ metallb_namespace }} \
      --atomic --timeout 10m

- name: Wait for metallb to be rolled out
  shell: >
    kubectl -n {{ metallb_namespace }} rollout status deploy/metallb-controller
  register: metallb_rollout_result
  retries: 5
  delay: 10
  until: "'successfully rolled out' in metallb_rollout_result.stdout"

- name: Create metallb ip-address-pool yaml file
  template:
    src: "ip-address-pool.yaml.j2"
    dest: "~/ip-address-pool.yaml"
  register: template_ip_address_pool

- name: Apply ip-address-pool
  shell: >-
    kubectl apply -f ~/ip-address-pool.yaml