---
- name: Include OS family vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Include OS distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "main.yml"

- name: Include platform-specific common tasks
  include_tasks: "_{{ ansible_os_family | lower }}.yml"

- name: Disable NFS v3
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sysconfig/nfs
    regexp: '^NFS3_SERVER_SUPPORT='
    line: NFS3_SERVER_SUPPORT="no"

- name: Ensure NFS share directory exists
  become: yes
  ansible.builtin.file:
    path: "{{ storage['nfs']['path'] | default('/nfs/share') }}"
    state: directory
    mode: 0777
    owner: nobody
    group: nobody

- name: Ensure database data folder exists
  become: yes
  ansible.builtin.file:
    path: "/var/lib/mysql"
    state: directory
    mode: 0777
    owner: nobody
    group: nobody
    recurse: yes

- name: Update /etc/exports
  become: yes
  blockinfile:
    path: /etc/exports
    block: |
      {{  storage['nfs']['path'] | default('/nfs/share') }} *(rw,sync,no_subtree_check,insecure)
      /var/lib/mysql *(rw,sync,no_subtree_check,insecure,all_squash,anonuid=0,anongid=60)

- name: restart NFS server
  become: yes
  ansible.builtin.service:
    name: nfs-server
    state: restarted
    enabled: true

- name: Export the share
  become: yes
  command: 'exportfs -rav'
