---
# NOTE(gyee): we'll only include the first one that matches. The rest will be ignored.
- name: Include OS family vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "main.yml"

- name: Include OS distribution vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower | replace(' ', '_') }}.yml"
    - "{{ ansible_distribution | replace(' ', '_') }}.yml"
    - "main.yml"

- name: Include platform-specific common tasks
  include_tasks: "_{{ ansible_os_family | lower }}.yml"

- name: Checkout local-path-provisioner repo
  include_role:
    name: baremetal
    tasks_from: checkout_repo
  vars:
    repo_dir: local-path-provisioner
    repo_url: "{{ local_path_provisioner_repo_url }}"
    repo_branch: "{{ local_path_provisioner_branch }}"
    repo_pull_request: "{{ local_path_provisioner_pull_request | default('') }}"

- name: Deploy local-path-provisioner via helm
  shell: >-
    env HELM_EXPERIMENTAL_OCI=1 \
    helm upgrade --install {{ local_path_provisioner_release }} ./deploy/chart/local-path-provisioner \
      --create-namespace --namespace {{ local_path_provisioner_namespace }} \
      --atomic --timeout 10m
  args:
    chdir: ~/local-path-provisioner
