---
# charts repo
baremetal_repo_url: https://github.com/suse-edge/charts.git
baremetal_branch: main

# metal3-demo repo
metal3_demo_repo_url: https://github.com/suse-edge/metal3-demo.git
metal3_demo_branch: main

# directories to create
directories_to_create:
  - /opt/images

# DNS zone forwarders
dns_zone_forwarders: []
